version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11.1

jobs:
  release:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Release with release-it
          command: npm run release -- --ci
          environment:
            NPM_TOKEN: $NPM_TOKEN
            GITHUB_TOKEN: $GH_TOKEN

workflows:
  version: 2
  release-workflow:
    jobs:
      - release:
          filters:
            branches:
              only: main