version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11.1

jobs:
  release:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Generate types
          command: npm run generate:types
      - run:
          name: Build SDK
          command: npm run build
      - run:
          name: Semantic Release
          command: npx semantic-release
          environment:
            NPM_TOKEN: $NPM_TOKEN
            GH_TOKEN: $GH_TOKEN

workflows:
  version: 2
  release-workflow:
    jobs:
      - release:
          filters:
            branches:
              only: main